### PR TITLE
Fixes BigNumber errors

### LINKED ISSUE #21: Dai transfer to 2 recipients, mainnet, metamask, doesn't work
```csv
token_address,receiver,amount,decimals
0x6b175474e89094c44da98b954eedeac495271d0f,0xDD00AB99Bff97E93AC1D0390F8e2ce41221050FE,21440,18
0x6b175474e89094c44da98b954eedeac495271d0f,0x77F6C1385eBd43ebe2B2de51C3E5d52cD4651278,19400,18
```
I realize the `decimals` column is unnecessary.

Here are the errors from the javascript console:
```javascript
Missing Infura key!
```
```javascript
Error: invalid BigNumber string (argument="value", value="2.144e+22", code=INVALID_ARGUMENT, version=bignumber/5.0.12)
```
```javascript
GET wss://mainnet.infura.io/ws/v3/undefined
```

The app worked 1 month ago (albeit with ETH, not DAI)

Using firefox, metamask

### PR DESCRIPTION
**Pull request by schmanu**
* toFixed instead of toString avoids exponential forms for big values

Closes #21

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
Looks good, but difficult to see the diff since the function was moved inside the app as a constant. Shall I assume the only difference is `toString -> toFixed`? Can we verify that this will resolve #21? Maybe we can include that file in the `test_data/` directory to be used later for regression testing.

File: src/App.tsx [hunk 1]
```diff
@@ -65,6 +33,47 @@ const App: React.FC = () => {
...
+            tokenList.get(transfer.tokenAddress)?.decimals || transfer.decimals
+          )
+        );
+        let amountData = transfer.amount.multipliedBy(exponent);
+        if (amountData.decimalPlaces() > 0) {
+          setLastError({
+            message:
+              "Precision too high. Some digits are ignored for row " + index,
+          });
+          amountData = amountData.decimalPlaces(0, BigNumber.ROUND_DOWN);
```
Comment (bh2smith) [inline src/App.tsx:62]: Nice catch!

**Comment by bh2smith** [comment]
I will deploy this as a new version and update the hash here. Hopefully we can come up with a better strategy for releases.

**Comment by bh2smith** [comment]
Thanks so much for finding this solution @schmanu! All ready for merge.
